name: auto-rebase
on:
  check_run:
    types:
      # Check runs completing successfully can unblock the corresponding pull requests and make them mergeable.
      - completed
  pull_request_review:
    types:
      # Review approvals can unblock the pull request and make it mergeable.
      - submitted
  # Success statuses can unblock the corresponding pull requests and make them mergeable.
  status: {}

jobs:
  auto-rebase:
    name: auto-rebase
    runs-on: ubuntu-latest
    steps:
      - uses: ovrsea/auto-rebase@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}