name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run check-prettier
      - name: Test
        run: npm run test